repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: check-merge-conflict
      - id: end-of-file-fixer
        exclude_types: [ "markdown", "json", "sql", "yaml", "xml" ]
      - id: trailing-whitespace
        exclude_types: [ "markdown", "json", "sql", "yaml", "xml" ]
      - id: check-xml
      - id: check-yaml
      - id: requirements-txt-fixer
      - id: mixed-line-ending
        args: [--fix=lf]
  - repo: https://github.com/ambv/black
    rev: 22.3.0
    hooks:
      - id: black
        name: black
        exclude: .venv|__pycache__
  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        name: flake8
        exclude: .venv|__pycache__
        args: ["--max-line-length=125"]
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.5.1
    hooks:
      - id: prettier
        exclude_types: ["markdown", "json", "yaml"]
